----------VIEWING THE TOP 12 ROWs OF THE DATA

  SELECT TOP (20)*
FROM energy_data

-------DROPPING THE NOTES COLUMN SINCE ITS ALL EMPTY AND VIEWING THE FIRST 12 ROWS AGAIN

ALTER TABLE energy_data
DROP COLUMN Notes

SELECT TOP (20)*
FROM energy_data
-----------

-----ANALYZING YEARLY ELECTRIC USAGE PATTERNS: TO GROUP THE DATA BY YEAR AND CALCULATE METRICS SUCH AS AVERAGE, MINIMUM, AND MAXIMUMELECTRIC USAGE FOR EACH YEAR

SELECT
DATEPART (year, Date) AS Year,
ROUND(AVG(Usage), 2) AS Avg_Usage,
MIN(Usage) AS Min_Usage,
MAX(Usage) AS Max_Usage
FROM energy_data
GROUP BY DATEPART (year, Date)
ORDER BY Year
---ANALYZING MONTHLY ELECTRIC USAGE PATTERNS: TO GROUP THE DATA BY MONTHS AND CALCULATE METRICS SUCH AS AVERAGE, MINIMUM, AND MAXIMUM ELECTRIC USAGE FOR EACH ACCUMULATED MONTH

SELECT
DATEPART (month, Date) AS Month,
ROUND(AVG(Usage), 2) AS Avg_Usage,
MIN(Usage) AS Min_USAGE,
MAX(Usage) AS Max_Usage
FROM energy_data
GROUP BY DATEPART (month, Date)
ORDER BY Month

----ANALYZING WEEKLY ELECTRIC USAGE PATTERNS: TO GROUP THE DATA BY WEEKDAY AND CALCULATE METRICS SUCH AS AVERAGE, MINIMUM, AND MAXIMUM ELECTRIC USAGE FOR EACH WEEKDAY

SELECT
DATEPART (weekday, Date) AS Week_day,
ROUND(AVG(Usage), 2) AS Avg_Usage,
MIN(Usage) AS Min_USAGE,
MAX(Usage) AS Max_Usage
FROM energy_data
GROUP BY DATEPART (weekday, Date)

----STANDARDIZING COST COLUMN

UPDATE energy_data
SET COST = REPLACE(COST,'$','') 

UPDATE energy_data
SET COST = TRIM(COST)

--------------ANALYZING COSTS ASSOCIATED WITH ELECTRIC USAGE: OVER YEARS

SELECT
DATEPART (year, Date) As Year,
ROUND(SUM(Usage), 2) AS Total_Usage,
ROUND(SUM(CAST(Cost AS FLOAT)), 2) AS Total_Cost
FROM energy_data
GROUP BY DATEPART (year, Date)

----ANALYZING COSTS ASSOCIATED WITH ELECTRIC USAGE: OVER MONTHS

SELECT
DATEPART (month, Date) As Month,
ROUND(SUM(Usage), 2) AS Total_Usage,
ROUND(SUM(CAST(COST AS FLOAT)), 2) AS Total_Cost
FROM energy_data
GROUP BY DATEPART (month, Date)
ORDER BY Total_Cost DESC

----------ANALYZING COSTS ASSOCIATED WITH ELECTRIC USAGE: OVER WEEKDAYS

SELECT
DATEPART (weekday, Date) As Week_Day,
ROUND(AVG(Usage), 2) AS Avg_Usage,
ROUND(SUM(Usage), 2) AS Total_Usage,
ROUND(AVG(CAST(Cost AS FLOAT)), 2) AS Avg_Cost,
ROUND(SUM(CAST(Cost AS FLOAT)), 2) AS Total_Cost
FROM energy_data
GROUP BY DATEPART (weekday, Date)
ORDER BY Total_Cost DESC